name: Docker image build and push to GHCR

on:
  workflow_dispatch:
  push:
    branches:
      - main  # 可以根据需要修改为其他分支

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64  # 增加 arm64 平台

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/phantun:latest
            ghcr.io/${{ github.repository_owner }}/phantun:${{ github.sha }}
          platforms: linux/amd64,linux/arm64  # 增加 arm64 平台
          push: true
